version: '3'

services:
 # web:
  #  build: .
  #  command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  #  volumes:
 #     - .:/app
 #   ports:
 #     - "8000:8000"
#    depends_on:
#      - my-postgres
#    environment:
#      - DJANGO_SETTINGS_MODULE=app.settings

  my-postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
