# Generated by Django 5.1.2 on 2025-08-26 12:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='uri',
            field=models.CharField(default='http://example.com/sotis/user/861d3868-a5e0-4674-93ff-785e08921232', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='context',
            field=models.CharField(default='lom:Higher_Education', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='lom:Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='intended_end_user_role',
            field=models.CharField(default='lom:Student', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='Final', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='typical_age_range',
            field=models.CharField(default='18-', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='typical_learning_time',
            field=models.CharField(default='PT5M', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='context',
            field=models.CharField(default='lom:Higher_Education', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='difficulty',
            field=models.CharField(default='lom:Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='intended_end_user_role',
            field=models.CharField(default='lom:Student', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(default='Final', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='typical_age_range',
            field=models.CharField(default='18-', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='typical_learning_time',
            field=models.CharField(default='PT30M', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='status',
            field=models.CharField(default='Final', max_length=50),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('expert', 'Expert'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='node_uri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='other_answers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='uri',
            field=models.CharField(default='http://example.com/sotis/question/bf221185-4d0c-44fe-9642-48980613d863', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='graph_uri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='uri',
            field=models.CharField(default='http://example.com/sotis/test/bf0601b0-656a-4d77-8664-6f6f8975f53a', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='app.test'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='uri',
            field=models.CharField(default='http://example.com/sotis/attempt/38ab9417-e2fb-46aa-bdd7-9e22cf08d23b', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.CharField(default='http://example.com/sotis/kg/da1e5b6e-7e5c-447d-a11d-b88769eafebb', max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('status', models.CharField(default='Final', max_length=50)),
                ('difficulty', models.CharField(default='lom:Medium', max_length=50)),
                ('context', models.CharField(default='lom:Higher_Education', max_length=50)),
                ('intended_end_user_role', models.CharField(default='lom:Student', max_length=50)),
                ('typical_age_range', models.CharField(default='18-', max_length=50)),
                ('typical_learning_time', models.CharField(default='PT1H', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='graph',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='app.knowledgegraph'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.CharField(default='http://example.com/sotis/node/e51b9fd3-111b-49ad-819d-f113d3eb6c9d', max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('graph_uri', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('status', models.CharField(default='Final', max_length=50)),
                ('difficulty', models.CharField(default='lom:Medium', max_length=50)),
                ('context', models.CharField(default='lom:Higher_Education', max_length=50)),
                ('intended_end_user_role', models.CharField(default='lom:Student', max_length=50)),
                ('typical_age_range', models.CharField(default='18-', max_length=50)),
                ('typical_learning_time', models.CharField(default='PT30M', max_length=50)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='app.knowledgegraph')),
                ('prerequisite_nodes', models.ManyToManyField(blank=True, to='app.node')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='node',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.node'),
            preserve_default=False,
        ),
    ]
