# Generated by Django 5.1.2 on 2025-08-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_test_questions_test_questions_old_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions_old',
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='tests', through='app.TestQuestion', to='app.question'),
        ),
    ]
