# Generated by Django 5.1.2 on 2025-08-26 14:48

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appuser_options_alter_testquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='uri',
            field=models.CharField(default=app.models.generate_user_uri, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='knowledgegraph',
            name='uri',
            field=models.CharField(default=app.models.generate_kg_uri, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='uri',
            field=models.CharField(default=app.models.generate_node_uri, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='uri',
            field=models.CharField(default=app.models.generate_question_uri, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='uri',
            field=models.CharField(default=app.models.generate_test_uri, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='uri',
            field=models.CharField(default=app.models.generate_test_attempt_uri, max_length=255, unique=True),
        ),
    ]
