# Generated by Django 5.1.2 on 2024-11-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_test_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphnode',
            name='prerequisite_nodes',
        ),
        migrations.AddField(
            model_name='graphnode',
            name='dependent_nodes',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_nodes', to='app.graphnode'),
        ),
    ]
